// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaqenazctethwgahxlwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhcWVuYXpjdGV0aHdnYWh4bHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NDk3OTYsImV4cCI6MjA2NDMyNTc5Nn0.ag-Py-qm8n1nnHxGIM1wOovPd-iNRrK0a4SU9A22zVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);